exports.seed = async (knex) => {
  await knex("products").insert([
    {
      name: "iPhone 15",
      price: 25000000,
      category: "Electronics",
      brand: "Apple",
      stock: 50,
    },
    {
      name: "Galaxy S24",
      price: 22000000,
      category: "Electronics",
      brand: "Samsung",
      stock: 40,
    },
    {
      name: "Laptop Gaming",
      price: 30000000,
      category: "Electronics",
      brand: "Asus",
      stock: 20,
    },
    {
      name: "Áo thun basic",
      price: 199000,
      category: "Clothing",
      brand: "Local Brand",
      stock: 100,
    },
    {
      name: "Quần jean",
      price: 399000,
      category: "Clothing",
      brand: "Levis",
      stock: 60,
    },
    {
      name: "Sách Clean Code",
      price: 280000,
      category: "Books",
      brand: "Prentice Hall",
      stock: 30,
    },
    {
      name: "Sách Design Patterns",
      price: 350000,
      category: "Books",
      brand: "Addison",
      stock: 25,
    },
    {
      name: "Bánh snack",
      price: 25000,
      category: "Food",
      brand: "Oishi",
      stock: 200,
    },
    {
      name: "Mì gói",
      price: 8000,
      category: "Food",
      brand: "Hảo Hảo",
      stock: 300,
    },
    {
      name: "Sữa hộp",
      price: 32000,
      category: "Food",
      brand: "Vinamilk",
      stock: 150,
    },
    {
      name: "Lego mini",
      price: 150000,
      category: "Toys",
      brand: "LEGO",
      stock: 50,
    },
    {
      name: "Gấu bông",
      price: 120000,
      category: "Toys",
      brand: "Teddy",
      stock: 80,
    },
    {
      name: "Tai nghe",
      price: 490000,
      category: "Electronics",
      brand: "Sony",
      stock: 70,
    },
    {
      name: "Giày thể thao",
      price: 890000,
      category: "Clothing",
      brand: "Nike",
      stock: 40,
    },
    {
      name: "Sách tiếng Anh",
      price: 180000,
      category: "Books",
      brand: "Cambridge",
      stock: 45,
    },
  ]);
};
